# Generated by Django 4.2.6 on 2024-02-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="TemplateDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("std_value", models.CharField(max_length=200)),
                ("obs_value", models.CharField(max_length=200)),
                ("start_time", models.CharField(max_length=200)),
                ("end_time", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_templatedetail",
            },
        ),
        migrations.CreateModel(
            name="TemplateMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="template name"
                    ),
                ),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "tbl_templatemaster",
            },
        ),
        migrations.CreateModel(
            name="Usertable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Type Name",
                    ),
                ),
                ("password", models.CharField(max_length=200)),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "tbl_usertable",
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_master",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.templatemaster",
                        verbose_name="template name",
                    ),
                ),
                (
                    "user_table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.usertable",
                        verbose_name="User name",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_userpermission",
            },
        ),
    ]
