# Generated by Django 4.2.6 on 2024-02-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
