# Generated by Django 4.2.6 on 2024-02-07 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_userpermission_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="select date"
            ),
        ),
    ]
