# Generated by Django 4.2.6 on 2024-02-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_userpermission_expiry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worksheet_name",
                    models.CharField(max_length=150, null=True, unique=True),
                ),
                (
                    "worksheet_file",
                    models.FileField(default=True, upload_to="template"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.usertable",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_uploadtemplate",
            },
        ),
    ]
