# Generated by Django 4.2.6 on 2024-02-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_uploadtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="template_master",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.uploadtemplate",
                verbose_name="template name",
            ),
        ),
    ]
