# Generated by Django 4.2.6 on 2024-02-10 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_formdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormData",
        ),
    ]
