# Generated by Django 4.2.6 on 2024-02-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_delete_formdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel"),
                            ("word", "Word"),
                            ("doc", "Doc"),
                            ("pdf", "PDF"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
