# Generated by Django 4.2.6 on 2024-02-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_formdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploaded_files/")),
            ],
        ),
        migrations.CreateModel(
            name="EditableForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_data", models.JSONField()),
                (
                    "uploaded_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
