# Generated by Django 4.2.6 on 2024-02-10 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_uploadedfile_editableform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editableform",
            name="uploaded_file",
        ),
        migrations.DeleteModel(
            name="FormData",
        ),
        migrations.DeleteModel(
            name="EditableForm",
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
