# Generated by Django 4.2.6 on 2024-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_editableform_uploaded_file_delete_formdata_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExcelData",
        ),
    ]
