# Generated by Django 4.2.6 on 2024-03-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_uploadtemplate_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=2000)),
                ("content", models.TextField(max_length=2000000)),
                (
                    "template_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.uploadtemplate",
                        verbose_name="template name",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_templatedata",
            },
        ),
    ]
