# Generated by Django 4.2.6 on 2024-03-15 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_templatedata"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="templatedata",
            table="tbl_tdata",
        ),
    ]
