# Generated by Django 4.2.6 on 2024-03-15 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_templatedata_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="templatedata",
            table="tbl_templatedata",
        ),
    ]
