# Generated by Django 4.2.6 on 2024-03-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_rename_templatemaster_formdata_template_master"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_name", models.CharField(max_length=150, null=True, unique=True)),
            ],
            options={
                "db_table": "tbl_form",
            },
        ),
    ]
