# Generated by Django 4.2.6 on 2024-03-18 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_uploadedform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemplateDetail",
        ),
        migrations.DeleteModel(
            name="TemplateMaster",
        ),
    ]
