# Generated by Django 4.2.6 on 2024-03-18 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_delete_templatedetail_delete_templatemaster"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemplateData",
        ),
    ]
