# Generated by Django 4.2.6 on 2024-03-18 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_tempdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempdata",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="select date"
            ),
        ),
    ]
