# Generated by Django 4.2.6 on 2024-03-18 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_tempdata_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempdata",
            name="expiry_date",
        ),
    ]
