# Generated by Django 4.2.6 on 2024-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_remove_tempdata_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="form_name",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
