# Generated by Django 4.2.6 on 2024-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_userpermission_form_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormDataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.CharField(max_length=50)),
                ("activity", models.TextField()),
                ("observation", models.TextField()),
                ("remark", models.TextField(blank=True)),
            ],
        ),
    ]
