# Generated by Django 4.2.6 on 2024-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_delete_formdataentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempdata",
            name="form_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.userpermission",
                verbose_name="form name",
            ),
        ),
    ]
