# Generated by Django 4.2.6 on 2024-03-18 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_tempdata_form_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempdata",
            name="form_name",
        ),
    ]
