# Generated by Django 4.2.6 on 2024-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_remove_tempdata_form_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempdata",
            name="fname",
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
