# Generated by Django 4.2.6 on 2024-03-18 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_tempdata_fname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempdata",
            name="fname",
        ),
    ]
