# Generated by Django 4.2.6 on 2024-03-18 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_templedata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TempData",
        ),
    ]
