# Generated by Django 4.2.6 on 2024-03-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_delete_tempdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.templedata",
                        verbose_name="template name",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_selectform",
            },
        ),
        migrations.DeleteModel(
            name="UploadedForm",
        ),
    ]
