# Generated by Django 4.2.6 on 2024-03-19 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_tempformrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermission",
            name="form_name",
        ),
    ]
