# Generated by Django 4.2.6 on 2024-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_remove_userpermission_form_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="form_name",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="TempFormRelation",
        ),
    ]
