# Generated by Django 4.2.6 on 2024-03-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_remove_userpermission_form_name_formdata_form_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formdata",
            name="form_name",
        ),
        migrations.AddField(
            model_name="templedata",
            name="form_data",
            field=models.TextField(max_length=9999999999999, null=True),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="form_name",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
