# Generated by Django 4.2.6 on 2024-03-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_remove_formdata_form_name_templedata_form_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_name", models.CharField(max_length=150, null=True, unique=True)),
            ],
            options={
                "db_table": "tbl_form_field",
            },
        ),
        migrations.CreateModel(
            name="UserPermissionFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.formfield"
                    ),
                ),
                (
                    "user_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userpermission",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_userpermission_formfield",
            },
        ),
    ]
