# Generated by Django 4.2.6 on 2024-03-19 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_formfield_userpermissionformfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermissionformfield",
            name="form_field",
        ),
        migrations.RemoveField(
            model_name="userpermissionformfield",
            name="user_permission",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
        migrations.DeleteModel(
            name="UserPermissionFormField",
        ),
    ]
