# Generated by Django 4.2.6 on 2024-03-19 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_remove_userpermissionformfield_form_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermission",
            name="form_name",
        ),
    ]
