# Generated by Django 4.2.6 on 2024-03-19 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_remove_userpermission_form_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templedata",
            name="form_data",
        ),
    ]
