# Generated by Django 4.2.6 on 2024-03-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_formdata_creator_formdata_form_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempFormRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.uploadedform",
                        verbose_name="form name",
                    ),
                ),
                (
                    "upload_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.uploadtemplate",
                        verbose_name="template name",
                    ),
                ),
                (
                    "user_table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.usertable",
                        verbose_name="User name",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tempformrelation",
            },
        ),
    ]
